// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLvCU0Y2NWH7gZjSzt_EVkAIMVgj2iX2k',
    appId: '1:264615602123:web:9bc22001d5f1d323a9784e',
    messagingSenderId: '264615602123',
    projectId: 'elbi-donate',
    authDomain: 'elbi-donate.firebaseapp.com',
    storageBucket: 'elbi-donate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-1dU_V2QDRNPLd72tYl5KiCg0e-RBk8',
    appId: '1:264615602123:android:d141d9599262434ca9784e',
    messagingSenderId: '264615602123',
    projectId: 'elbi-donate',
    storageBucket: 'elbi-donate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkFCQEGLxZ5OdIXPRiayoJK37wUgYZOZg',
    appId: '1:264615602123:ios:67f94a28c4b04ca5a9784e',
    messagingSenderId: '264615602123',
    projectId: 'elbi-donate',
    storageBucket: 'elbi-donate.appspot.com',
    iosBundleId: 'com.example.elbiDonate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkFCQEGLxZ5OdIXPRiayoJK37wUgYZOZg',
    appId: '1:264615602123:ios:67f94a28c4b04ca5a9784e',
    messagingSenderId: '264615602123',
    projectId: 'elbi-donate',
    storageBucket: 'elbi-donate.appspot.com',
    iosBundleId: 'com.example.elbiDonate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLvCU0Y2NWH7gZjSzt_EVkAIMVgj2iX2k',
    appId: '1:264615602123:web:98078c6e840a8e3aa9784e',
    messagingSenderId: '264615602123',
    projectId: 'elbi-donate',
    authDomain: 'elbi-donate.firebaseapp.com',
    storageBucket: 'elbi-donate.appspot.com',
  );

}