// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm4T6x2LXNYriRX_OH4Kmggzqs1VwXbqE',
    appId: '1:799462313987:web:57d25c009d43b8a3ed3e36',
    messagingSenderId: '799462313987',
    projectId: 'elbi-donation-system',
    authDomain: 'elbi-donation-system.firebaseapp.com',
    storageBucket: 'elbi-donation-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmeFQunHXHUjNXFzuclNkQpWSsa-lrEts',
    appId: '1:799462313987:android:0a971c15a7502505ed3e36',
    messagingSenderId: '799462313987',
    projectId: 'elbi-donation-system',
    storageBucket: 'elbi-donation-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3M3cCBmQosfH5zqLdRJECdt8mFMpmqxk',
    appId: '1:799462313987:ios:828ac7138a467c4bed3e36',
    messagingSenderId: '799462313987',
    projectId: 'elbi-donation-system',
    storageBucket: 'elbi-donation-system.appspot.com',
    iosBundleId: 'com.example.elbiDonate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3M3cCBmQosfH5zqLdRJECdt8mFMpmqxk',
    appId: '1:799462313987:ios:828ac7138a467c4bed3e36',
    messagingSenderId: '799462313987',
    projectId: 'elbi-donation-system',
    storageBucket: 'elbi-donation-system.appspot.com',
    iosBundleId: 'com.example.elbiDonate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm4T6x2LXNYriRX_OH4Kmggzqs1VwXbqE',
    appId: '1:799462313987:web:98034e92cfa4e467ed3e36',
    messagingSenderId: '799462313987',
    projectId: 'elbi-donation-system',
    authDomain: 'elbi-donation-system.firebaseapp.com',
    storageBucket: 'elbi-donation-system.appspot.com',
  );
}
